# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/BlockLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 30
Metrics/ClassLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
Layout/EndOfLine:
  EnforcedStyle: lf
Security/MarshalLoad:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: true
require: []
